version: "3.8"

services:
  disaster-management-app:
    build: .  # Build from the Dockerfile in the current directory
    container_name: disaster-management-app
    ports:
      - "5050:5050"
    depends_on:
      - prometheus
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/config/prometheus.yml  # Mount to a new location
    command:
      - '--config.file=/etc/prometheus/config/prometheus.yml'  # Tell Prometheus to use the new location
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"  # Enable anonymous access (for testing only)
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  grafana_data:
